name: Validar Mensagens de Commit no PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validar-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Executar script de validação
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          TARGET_BRANCH: ${{ github.base_ref }}
        run: python scripts/script-valida-pr.py